repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v3.0.3' # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier-plugin-svelte@3.0.3
          - prettier-plugin-tailwindcss@0.5.6
        args:
          - '--plugin=prettier-plugin-svelte'
          - '--plugin=prettier-plugin-tailwindcss'

  - repo: https://github.com/eslint/eslint
    rev: 'v8.52.0' # Use the sha or tag you want to point at
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint-config-prettier@9.0.0
          - eslint-plugin-svelte@2.34.0
        args:
          - '--config=.eslintrc.cjs'
        types:
          - file
        files: \.(js|ts|svelte)$
