backend:
  name: git-gateway
  branch: master

local_backend: true
media_folder: src/media
public_folder: /media

collections:
  - name: pages
    label: Pages
    editor:
      preview: false
    files:
      - file: 'src/lib/meta.json'
        label: Meta
        name: meta
        fields:
          - {
              label: Header Photo,
              name: headerPhoto,
              widget: image,
              help: This image must have a 2:1 width to height ratio (i.e. 2000x1000 or 3000x1500)
            }
          - { label: Header Photo Alt Text, name: headerPhotoAltText, widget: string }
      - file: 'src/routes/home.json'
        label: Home Page
        name: index
        fields:
          - {
              label: Meta Description,
              name: metaDescription,
              widget: string,
              hint: A descriptive sentence or two used by search engines to index the page.
            }
          - { label: Header Image, name: headerImage, widget: image }
          - { label: Header Image Alt Text, name: headerImageAltText, widget: string }
          - { label: Body, name: body, widget: markdown }
      - file: 'src/routes/about/about.json'
        label: About
        name: about
        fields:
          - {
              label: Meta Description,
              name: metaDescription,
              widget: string,
              hint: A descriptive sentence or two used by search engines to index the page.
            }
          - { label: Body, name: body, widget: markdown }
          - label: Articles
            name: articles
            widget: list
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Link, name: link, widget: string }
              - { label: Photo, name: photo, widget: image }
      - file: 'src/routes/events/events.json'
        label: Events
        name: events
        fields:
          - {
              label: Meta Description,
              name: metaDescription,
              widget: string,
              hint: A descriptive sentence or two used by search engines to index the page.
            }
          - { label: Body, name: body, widget: markdown }
      - file: 'src/routes/contact/contact.json'
        label: Contact
        name: contact
        fields:
          - {
              label: Meta Description,
              name: metaDescription,
              widget: string,
              hint: A descriptive sentence or two used by search engines to index the page.
            }
          - {
              label: Custom Header Photo,
              name: customHeaderPhoto,
              widget: image,
              help: This image must have a 2:1 width to height ratio (i.e. 2000x1000 or 3000x1500
            }
          - { label: Custom Header Photo Alt Text, name: customHeaderPhotoAltText, widget: string }
          - { label: Body, name: body, widget: markdown }
          - { label: Form Title, name: formTitle, widget: string }
          - { label: Success Message, name: successMessage, widget: markdown }
